services:
  web:
    build: ./containers/php
    container_name: lamp_web
    ports:
      - "8080:80"
    volumes:
      - ./mealtracker:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mealtracker
      MYSQL_USER: mealtracker
      MYSQL_PASSWORD: mealtracker
    ports:
      - "3306:3306"
    volumes:
      - ./var_mysql:/var/lib/mysql
